// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/metastore/v1alpha/metastore.proto

package com.google.cloud.metastore.v1alpha;

public interface MetadataIntegrationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.metastore.v1alpha.MetadataIntegration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The integration config for the Data Catalog service.
   * </pre>
   *
   * <code>.google.cloud.metastore.v1alpha.DataCatalogConfig data_catalog_config = 1;</code>
   * @return Whether the dataCatalogConfig field is set.
   */
  boolean hasDataCatalogConfig();
  /**
   * <pre>
   * The integration config for the Data Catalog service.
   * </pre>
   *
   * <code>.google.cloud.metastore.v1alpha.DataCatalogConfig data_catalog_config = 1;</code>
   * @return The dataCatalogConfig.
   */
  com.google.cloud.metastore.v1alpha.DataCatalogConfig getDataCatalogConfig();
  /**
   * <pre>
   * The integration config for the Data Catalog service.
   * </pre>
   *
   * <code>.google.cloud.metastore.v1alpha.DataCatalogConfig data_catalog_config = 1;</code>
   */
  com.google.cloud.metastore.v1alpha.DataCatalogConfigOrBuilder getDataCatalogConfigOrBuilder();
}
