/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/metastore/v1beta/metastore.proto

package com.google.cloud.metastore.v1beta;

public final class MetastoreProto {
  private MetastoreProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_Service_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_Service_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_Service_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_Service_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_MetadataIntegration_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_MetadataIntegration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_DataCatalogConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_DataCatalogConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_MaintenanceWindow_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_MaintenanceWindow_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_HiveMetastoreConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_HiveMetastoreConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_HiveMetastoreConfig_ConfigOverridesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_HiveMetastoreConfig_ConfigOverridesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_KerberosConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_KerberosConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_Secret_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_Secret_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_MetadataManagementActivity_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_MetadataManagementActivity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_MetadataImport_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_MetadataImport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_MetadataImport_DatabaseDump_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_MetadataImport_DatabaseDump_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_MetadataExport_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_MetadataExport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_Backup_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_Backup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_Restore_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_Restore_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_ListServicesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_ListServicesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_ListServicesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_ListServicesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_GetServiceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_GetServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_CreateServiceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_CreateServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_UpdateServiceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_UpdateServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_DeleteServiceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_DeleteServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_ListMetadataImportsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_ListMetadataImportsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_ListMetadataImportsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_ListMetadataImportsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_GetMetadataImportRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_GetMetadataImportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_CreateMetadataImportRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_CreateMetadataImportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_UpdateMetadataImportRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_UpdateMetadataImportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_ListBackupsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_ListBackupsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_ListBackupsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_ListBackupsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_GetBackupRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_GetBackupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_CreateBackupRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_CreateBackupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_DeleteBackupRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_DeleteBackupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_ExportMetadataRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_ExportMetadataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_RestoreServiceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_RestoreServiceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_OperationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_OperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_LocationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_LocationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_LocationMetadata_HiveMetastoreVersion_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_LocationMetadata_HiveMetastoreVersion_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_metastore_v1beta_DatabaseDumpSpec_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_metastore_v1beta_DatabaseDumpSpec_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n"
          + "-google/cloud/metastore/v1beta/metastor"
          + "e.proto\022\035google.cloud.metastore.v1beta\032\034"
          + "google/api/annotations.proto\032\027google/api"
          + "/client.proto\032\037google/api/field_behavior"
          + ".proto\032\031google/api/resource.proto\032#google/longrunning/operations.proto\032"
          + " google/protobuf/field_mask.proto\032\037google/protobu"
          + "f/timestamp.proto\032\036google/protobuf/wrappers.proto\032\033google/type/dayofweek.proto\"\326\n\n"
          + "\007Service\022S\n"
          + "\025hive_metastore_config\030\005"
          + " \001(\01322.google.cloud.metastore.v1beta.HiveMetastoreConfigH\000\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\005\0224\n"
          + "\013create_time\030\002 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0224\n"
          + "\013update_time\030\003 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022B\n"
          + "\006labels\030\004"
          + " \003(\01322.google.cloud.metastore.v1beta.Service.LabelsEntry\0227\n"
          + "\007network\030\007 \001(\tB&\340A\005\372A \n"
          + "\036compute.googleapis.com/Network\022\031\n"
          + "\014endpoint_uri\030\010 \001(\tB\003\340A\003\022\014\n"
          + "\004port\030\t \001(\005\022@\n"
          + "\005state\030\n"
          + " \001(\0162,.google.cloud.metastore.v1beta.Service.StateB\003\340A\003\022\032\n\r"
          + "state_message\030\013 \001(\tB\003\340A\003\022\035\n"
          + "\020artifact_gcs_uri\030\014 \001(\tB\003\340A\003\0229\n"
          + "\004tier\030\r"
          + " \001(\0162+.google.cloud.metastore.v1beta.Service.Tier\022P\n"
          + "\024metadata_integration\030\016"
          + " \001(\01322.google.cloud.metastore.v1beta.MetadataIntegration\022L\n"
          + "\022maintenance_window\030\017"
          + " \001(\01320.google.cloud.metastore.v1beta.MaintenanceWindow\022\020\n"
          + "\003uid\030\020 \001(\tB\003\340A\003\022d\n"
          + "\034metadata_management_activity\030\021"
          + " \001(\01329.google.cloud.metastore.v1beta.MetadataManagementActivityB\003\340A\003\022S\n"
          + "\017release_channel\030\023"
          + " \001(\01625.google.cloud.metastore.v1beta.Service.ReleaseChannelB\003\340A\005\032-\n"
          + "\013LabelsEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"~\n"
          + "\005State\022\025\n"
          + "\021STATE_UNSPECIFIED\020\000\022\014\n"
          + "\010CREATING\020\001\022\n\n"
          + "\006ACTIVE\020\002\022\016\n\n"
          + "SUSPENDING\020\003\022\r\n"
          + "\tSUSPENDED\020\004\022\014\n"
          + "\010UPDATING\020\005\022\014\n"
          + "\010DELETING\020\006\022\t\n"
          + "\005ERROR\020\007\";\n"
          + "\004Tier\022\024\n"
          + "\020TIER_UNSPECIFIED\020\000\022\r\n"
          + "\tDEVELOPER\020\001\022\016\n"
          + "\n"
          + "ENTERPRISE\020\003\"I\n"
          + "\016ReleaseChannel\022\037\n"
          + "\033RELEASE_CHANNEL_UNSPECIFIED\020\000\022\n\n"
          + "\006CANARY\020\001\022\n\n"
          + "\006STABLE\020\002:a\352A^\n"
          + " metastore.googleapis.com/Service\022:projects/{project}/locations/{location}/services/{service}B\022\n"
          + "\020metastore_config\"d\n"
          + "\023MetadataIntegration\022M\n"
          + "\023data_catalog_config\030\001"
          + " \001(\01320.google.cloud.metastore.v1beta.DataCatalogConfig\"$\n"
          + "\021DataCatalogConfig\022\017\n"
          + "\007enabled\030\002 \001(\010\"r\n"
          + "\021MaintenanceWindow\0220\n"
          + "\013hour_of_day\030\001 \001(\0132\033.google.protobuf.Int32Value\022+\n"
          + "\013day_of_week\030\002 \001(\0162\026.google.type.DayOfWeek\"\216\002\n"
          + "\023HiveMetastoreConfig\022\024\n"
          + "\007version\030\001 \001(\tB\003\340A\005\022a\n"
          + "\020config_overrides\030\002"
          + " \003(\0132G.google.cloud.metastore.v1beta.HiveMetastoreConfig.ConfigOverridesEntry\022F\n"
          + "\017kerberos_config\030\003"
          + " \001(\0132-.google.cloud.metastore.v1beta.KerberosConfig\0326\n"
          + "\024ConfigOverridesEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"w\n"
          + "\016KerberosConfig\0225\n"
          + "\006keytab\030\001 \001(\0132%.google.cloud.metastore.v1beta.Secret\022\021\n"
          + "\tprincipal\030\002 \001(\t\022\033\n"
          + "\023krb5_config_gcs_uri\030\003 \001(\t\")\n"
          + "\006Secret\022\026\n"
          + "\014cloud_secret\030\002 \001(\tH\000B\007\n"
          + "\005value\"\251\001\n"
          + "\032MetadataManagementActivity\022L\n"
          + "\020metadata_exports\030\001"
          + " \003(\0132-.google.cloud.metastore.v1beta.MetadataExportB\003\340A\003\022=\n"
          + "\010restores\030\002"
          + " \003(\0132&.google.cloud.metastore.v1beta.RestoreB\003\340A\003\"\335\006\n"
          + "\016MetadataImport\022X\n\r"
          + "database_dump\030\006"
          + " \001(\0132:.google.cloud.metastore.v1beta.MetadataImport.DatabaseDumpB\003\340A\005H\000\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\005\022\023\n"
          + "\013description\030\002 \001(\t\0224\n"
          + "\013create_time\030\003 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0224\n"
          + "\013update_time\030\004 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022G\n"
          + "\005state\030\005"
          + " \001(\01623.google.cloud.metastore.v1beta.MetadataImport.StateB\003\340A\003\032\243\002\n"
          + "\014DatabaseDump\022b\n\r"
          + "database_type\030\001"
          + " \001(\0162G.google.cloud.metastore.v1beta.MetadataImport.DatabaseDump.DatabaseTypeB\002\030\001\022\017\n"
          + "\007gcs_uri\030\002 \001(\t\022\033\n"
          + "\017source_database\030\003 \001(\tB\002\030\001\022G\n"
          + "\004type\030\004"
          + " \001(\01624.google.cloud.metastore.v1beta.DatabaseDumpSpec.TypeB\003\340A\001\"8\n"
          + "\014DatabaseType\022\035\n"
          + "\031DATABASE_TYPE_UNSPECIFIED\020\000\022\t\n"
          + "\005MYSQL\020\001\"T\n"
          + "\005State\022\025\n"
          + "\021STATE_UNSPECIFIED\020\000\022\013\n"
          + "\007RUNNING\020\001\022\r\n"
          + "\tSUCCEEDED\020\002\022\014\n"
          + "\010UPDATING\020\003\022\n\n"
          + "\006FAILED\020\004:\213\001\352A\207\001\n"
          + "\'metastore.googleapis.com/MetadataImport\022\\projects"
          + "/{project}/locations/{location}/services/{service}/metadataImports/{metadata_import}B\n\n"
          + "\010metadata\"\242\003\n"
          + "\016MetadataExport\022\"\n"
          + "\023destination_gcs_uri\030\004 \001(\tB\003\340A\003H\000\0223\n\n"
          + "start_time\030\001 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0221\n"
          + "\010end_time\030\002 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022G\n"
          + "\005state\030\003"
          + " \001(\01623.google.cloud.metastore.v1beta.MetadataExport.StateB\003\340A\003\022U\n"
          + "\022database_dump_type\030\005"
          + " \001(\01624.google.cloud.metastore.v1beta.DatabaseDumpSpec.TypeB\003\340A\003\"U\n"
          + "\005State\022\025\n"
          + "\021STATE_UNSPECIFIED\020\000\022\013\n"
          + "\007RUNNING\020\001\022\r\n"
          + "\tSUCCEEDED\020\002\022\n\n"
          + "\006FAILED\020\003\022\r\n"
          + "\tCANCELLED\020\004B\r\n"
          + "\013destination\"\350\003\n"
          + "\006Backup\022\021\n"
          + "\004name\030\001 \001(\tB\003\340A\005\0224\n"
          + "\013create_time\030\002 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0221\n"
          + "\010end_time\030\003 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022?\n"
          + "\005state\030\004"
          + " \001(\0162+.google.cloud.metastore.v1beta.Backup.StateB\003\340A\003\022E\n"
          + "\020service_revision\030\005"
          + " \001(\0132&.google.cloud.metastore.v1beta.ServiceB\003\340A\003\022\023\n"
          + "\013description\030\006 \001(\t\"R\n"
          + "\005State\022\025\n"
          + "\021STATE_UNSPECIFIED\020\000\022\014\n"
          + "\010CREATING\020\001\022\014\n"
          + "\010DELETING\020\002\022\n\n"
          + "\006ACTIVE\020\003\022\n\n"
          + "\006FAILED\020\004:q\352An\n"
          + "\037metastore.googleapis.com/Backup\022Kprojects/{project}/locations/{location}/services/{service}/backups/{backup}\"\352\003\n"
          + "\007Restore\0223\n\n"
          + "start_time\030\001 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0221\n"
          + "\010end_time\030\002 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022@\n"
          + "\005state\030\003"
          + " \001(\0162,.google.cloud.metastore.v1beta.Restore.StateB\003\340A\003\0227\n"
          + "\006backup\030\004 \001(\tB\'\340A\003\372A!\n"
          + "\037metastore.googleapis.com/Backup\022E\n"
          + "\004type\030\005"
          + " \001(\01622.google.cloud.metastore.v1beta.Restore.RestoreTypeB\003\340A\003\022\024\n"
          + "\007details\030\006 \001(\tB\003\340A\003\"U\n"
          + "\005State\022\025\n"
          + "\021STATE_UNSPECIFIED\020\000\022\013\n"
          + "\007RUNNING\020\001\022\r\n"
          + "\tSUCCEEDED\020\002\022\n\n"
          + "\006FAILED\020\003\022\r\n"
          + "\tCANCELLED\020\004\"H\n"
          + "\013RestoreType\022\034\n"
          + "\030RESTORE_TYPE_UNSPECIFIED\020\000\022\010\n"
          + "\004FULL\020\001\022\021\n\r"
          + "METADATA_ONLY\020\002\"\255\001\n"
          + "\023ListServicesRequest\0229\n"
          + "\006parent\030\001 \001(\tB)\340A\002\372A#\n"
          + "!locations.googleapis.com/Location\022\026\n"
          + "\tpage_size\030\002 \001(\005B\003\340A\001\022\027\n\n"
          + "page_token\030\003 \001(\tB\003\340A\001\022\023\n"
          + "\006filter\030\004 \001(\tB\003\340A\001\022\025\n"
          + "\010order_by\030\005 \001(\tB\003\340A\001\"~\n"
          + "\024ListServicesResponse\0228\n"
          + "\010services\030\001 \003(\0132&.google.cloud.metastore.v1beta.Service\022\027\n"
          + "\017next_page_token\030\002 \001(\t\022\023\n"
          + "\013unreachable\030\003 \003(\t\"K\n"
          + "\021GetServiceRequest\0226\n"
          + "\004name\030\001 \001(\tB(\340A\002\372A\"\n"
          + " metastore.googleapis.com/Service\"\301\001\n"
          + "\024CreateServiceRequest\0229\n"
          + "\006parent\030\001 \001(\tB)\340A\002\372A#\n"
          + "!locations.googleapis.com/Location\022\027\n\n"
          + "service_id\030\002 \001(\tB\003\340A\002\022<\n"
          + "\007service\030\003"
          + " \001(\0132&.google.cloud.metastore.v1beta.ServiceB\003\340A\002\022\027\n\n"
          + "request_id\030\004 \001(\tB\003\340A\001\"\243\001\n"
          + "\024UpdateServiceRequest\0224\n"
          + "\013update_mask\030\001 \001(\0132\032.google.protobuf.FieldMaskB\003\340A\002\022<\n"
          + "\007service\030\002"
          + " \001(\0132&.google.cloud.metastore.v1beta.ServiceB\003\340A\002\022\027\n\n"
          + "request_id\030\003 \001(\tB\003\340A\001\"g\n"
          + "\024DeleteServiceRequest\0226\n"
          + "\004name\030\001 \001(\tB(\340A\002\372A\"\n"
          + " metastore.googleapis.com/Service\022\027\n\n"
          + "request_id\030\002 \001(\tB\003\340A\001\"\263\001\n"
          + "\032ListMetadataImportsRequest\0228\n"
          + "\006parent\030\001 \001(\tB(\340A\002\372A\"\n"
          + " metastore.googleapis.com/Service\022\026\n"
          + "\tpage_size\030\002 \001(\005B\003\340A\001\022\027\n\n"
          + "page_token\030\003 \001(\tB\003\340A\001\022\023\n"
          + "\006filter\030\004 \001(\tB\003\340A\001\022\025\n"
          + "\010order_by\030\005 \001(\tB\003\340A\001\"\224\001\n"
          + "\033ListMetadataImportsResponse\022G\n"
          + "\020metadata_imports\030\001"
          + " \003(\0132-.google.cloud.metastore.v1beta.MetadataImport\022\027\n"
          + "\017next_page_token\030\002 \001(\t\022\023\n"
          + "\013unreachable\030\003 \003(\t\"Y\n"
          + "\030GetMetadataImportRequest\022=\n"
          + "\004name\030\001 \001(\tB/\340A\002\372A)\n"
          + "\'metastore.googleapis.com/MetadataImport\"\336\001\n"
          + "\033CreateMetadataImportRequest\0228\n"
          + "\006parent\030\001 \001(\tB(\340A\002\372A\"\n"
          + " metastore.googleapis.com/Service\022\037\n"
          + "\022metadata_import_id\030\002 \001(\tB\003\340A\002\022K\n"
          + "\017metadata_import\030\003"
          + " \001(\0132-.google.cloud.metastore.v1beta.MetadataImportB\003\340A\002\022\027\n\n"
          + "request_id\030\004 \001(\tB\003\340A\001\"\271\001\n"
          + "\033UpdateMetadataImportRequest\0224\n"
          + "\013update_mask\030\001 \001(\0132\032.google.protobuf.FieldMaskB\003\340A\002\022K\n"
          + "\017metadata_import\030\002"
          + " \001(\0132-.google.cloud.metastore.v1beta.MetadataImportB\003\340A\002\022\027\n\n"
          + "request_id\030\003 \001(\tB\003\340A\001\"\253\001\n"
          + "\022ListBackupsRequest\0228\n"
          + "\006parent\030\001 \001(\tB(\340A\002\372A\"\n"
          + " metastore.googleapis.com/Service\022\026\n"
          + "\tpage_size\030\002 \001(\005B\003\340A\001\022\027\n\n"
          + "page_token\030\003 \001(\tB\003\340A\001\022\023\n"
          + "\006filter\030\004 \001(\tB\003\340A\001\022\025\n"
          + "\010order_by\030\005 \001(\tB\003\340A\001\"{\n"
          + "\023ListBackupsResponse\0226\n"
          + "\007backups\030\001 \003(\0132%.google.cloud.metastore.v1beta.Backup\022\027\n"
          + "\017next_page_token\030\002 \001(\t\022\023\n"
          + "\013unreachable\030\003 \003(\t\"I\n"
          + "\020GetBackupRequest\0225\n"
          + "\004name\030\001 \001(\tB\'\340A\002\372A!\n"
          + "\037metastore.googleapis.com/Backup\"\274\001\n"
          + "\023CreateBackupRequest\0228\n"
          + "\006parent\030\001 \001(\tB(\340A\002\372A\"\n"
          + " metastore.googleapis.com/Service\022\026\n"
          + "\tbackup_id\030\002 \001(\tB\003\340A\002\022:\n"
          + "\006backup\030\003"
          + " \001(\0132%.google.cloud.metastore.v1beta.BackupB\003\340A\002\022\027\n\n"
          + "request_id\030\004 \001(\tB\003\340A\001\"e\n"
          + "\023DeleteBackupRequest\0225\n"
          + "\004name\030\001 \001(\tB\'\340A\002\372A!\n"
          + "\037metastore.googleapis.com/Backup\022\027\n\n"
          + "request_id\030\002 \001(\tB\003\340A\001\"\363\001\n"
          + "\025ExportMetadataRequest\022 \n"
          + "\026destination_gcs_folder\030\002 \001(\tH\000\0229\n"
          + "\007service\030\001 \001(\tB(\340A\002\372A\"\n"
          + " metastore.googleapis.com/Service\022\027\n\n"
          + "request_id\030\003 \001(\tB\003\340A\001\022U\n"
          + "\022database_dump_type\030\004"
          + " \001(\01624.google.cloud.metastore.v1beta.DatabaseDumpSpec.TypeB\003\340A\001B\r\n"
          + "\013destination\"\363\001\n"
          + "\025RestoreServiceRequest\0229\n"
          + "\007service\030\001 \001(\tB(\340A\002\372A\"\n"
          + " metastore.googleapis.com/Service\0227\n"
          + "\006backup\030\002 \001(\tB\'\340A\002\372A!\n"
          + "\037metastore.googleapis.com/Backup\022M\n"
          + "\014restore_type\030\003"
          + " \001(\01622.google.cloud.metastore.v1beta.Restore.RestoreTypeB\003\340A\001\022\027\n\n"
          + "request_id\030\004 \001(\tB\003\340A\001\"\200\002\n"
          + "\021OperationMetadata\0224\n"
          + "\013create_time\030\001 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0221\n"
          + "\010end_time\030\002 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022\023\n"
          + "\006target\030\003 \001(\tB\003\340A\003\022\021\n"
          + "\004verb\030\004 \001(\tB\003\340A\003\022\033\n"
          + "\016status_message\030\005 \001(\tB\003\340A\003\022#\n"
          + "\026requested_cancellation\030\006 \001(\010B\003\340A\003\022\030\n"
          + "\013api_version\030\007 \001(\tB\003\340A\003\"\300\001\n"
          + "\020LocationMetadata\022o\n"
          + "!supported_hive_metastore_versions\030\001"
          + " \003(\0132D.google.cloud.metastore.v1beta.LocationMetadata.HiveMetastoreVersion\032;\n"
          + "\024HiveMetastoreVersion\022\017\n"
          + "\007version\030\001 \001(\t\022\022\n\n"
          + "is_default\030\002 \001(\010\";\n"
          + "\020DatabaseDumpSpec\"\'\n"
          + "\004Type\022\024\n"
          + "\020TYPE_UNSPECIFIED\020\000\022\t\n"
          + "\005MYSQL\020\0012\334\032\n"
          + "\021DataprocMetastore\022\272\001\n"
          + "\014ListServices\0222.google.cloud.metastore.v1beta.ListServicesRequest\0323.googl"
          + "e.cloud.metastore.v1beta.ListServicesResponse\"A\202\323\344\223\0022\0220/v1beta/{parent=projects/*/locations/*}/services\332A\006parent\022\247\001\n\n"
          + "GetService\0220.google.cloud.metastore.v1beta."
          + "GetServiceRequest\032&.google.cloud.metasto"
          + "re.v1beta.Service\"?\202\323\344\223\0022\0220/v1beta/{name=projects/*/locations/*/services/*}\332A\004name\022\341\001\n\r"
          + "CreateService\0223.google.cloud.metastore.v1beta.CreateServiceRequest\032\035.goog"
          + "le.longrunning.Operation\"|\202\323\344\223\002;\"0/v1bet"
          + "a/{parent=projects/*/locations/*}/services:\007service\332A\031parent,service,service_id\312A\034\n"
          + "\007Service\022\021OperationMetadata\022\343\001\n\r"
          + "UpdateService\0223.google.cloud.metastore.v1beta"
          + ".UpdateServiceRequest\032\035.google.longrunni"
          + "ng.Operation\"~\202\323\344\223\002C28/v1beta/{service.name=projects/*/locations/*/services/*}:\007service\332A\023service,update_mask\312A\034\n"
          + "\007Service\022\021OperationMetadata\022\321\001\n\r"
          + "DeleteService\0223.google.cloud.metastore.v1beta.DeleteSer"
          + "viceRequest\032\035.google.longrunning.Operation\"l\202\323\344\223\0022*0/v1beta/{name=projects/*/locations/*/services/*}\332A\004name\312A*\n"
          + "\025google.protobuf.Empty\022\021OperationMetadata\022\341\001\n"
          + "\023ListMetadataImports\0229.google.cloud.metastor"
          + "e.v1beta.ListMetadataImportsRequest\032:.google.cloud.metastore.v1beta.ListMetadata"
          + "ImportsResponse\"S\202\323\344\223\002D\022B/v1beta/{parent=projects/*/locations/*/services/*}/metadataImports\332A\006parent\022\316\001\n"
          + "\021GetMetadataImport\0227.google.cloud.metastore.v1beta.GetMe"
          + "tadataImportRequest\032-.google.cloud.metas"
          + "tore.v1beta.MetadataImport\"Q\202\323\344\223\002D\022B/v1beta/{name=projects/*/locations/*/services/*/metadataImports/*}\332A\004name\022\241\002\n"
          + "\024CreateMetadataImport\022:.google.cloud.metastore."
          + "v1beta.CreateMetadataImportRequest\032\035.goo"
          + "gle.longrunning.Operation\"\255\001\202\323\344\223\002U\"B/v1b"
          + "eta/{parent=projects/*/locations/*/services/*}/metadataImports:\017metadata_import\332A)parent,metadata_import,metadata_import_id\312A#\n"
          + "\016MetadataImport\022\021OperationMetadata\022\243\002\n"
          + "\024UpdateMetadataImport\022:.google.cloud.metastore.v1beta.UpdateMetadataImportR"
          + "equest\032\035.google.longrunning.Operation\"\257\001"
          + "\202\323\344\223\002e2R/v1beta/{metadata_import.name=pr"
          + "ojects/*/locations/*/services/*/metadataImports/*}:\017metadata_import\332A\033metadata_import,update_mask\312A#\n"
          + "\016MetadataImport\022\021OperationMetadata\022\332\001\n"
          + "\016ExportMetadata\0224.google.cloud.metastore.v1beta.ExportMetadat"
          + "aRequest\032\035.google.longrunning.Operation\""
          + "s\202\323\344\223\002G\"B/v1beta/{service=projects/*/locations/*/services/*}:exportMetadata:\001*\312A#\n"
          + "\016MetadataExport\022\021OperationMetadata\022\335\001\n"
          + "\016RestoreService\0224.google.cloud.metastore"
          + ".v1beta.RestoreServiceRequest\032\035.google.l"
          + "ongrunning.Operation\"v\202\323\344\223\002@\";/v1beta/{service=projects/*/locations/*/services/*}:restore:\001*\332A\016service,backup\312A\034\n"
          + "\007Restore\022\021OperationMetadata\022\301\001\n"
          + "\013ListBackups\0221.google.cloud.metastore.v1beta.ListBackups"
          + "Request\0322.google.cloud.metastore.v1beta."
          + "ListBackupsResponse\"K\202\323\344\223\002<\022:/v1beta/{parent=projects/*/locations/*/services/*}/backups\332A\006parent\022\256\001\n"
          + "\tGetBackup\022/.google.cloud.metastore.v1beta.GetBackupRequest\032"
          + "%.google.cloud.metastore.v1beta.Backup\"I\202\323\344\223\002<\022:/v1beta/{name=projects/*/locations/*/services/*/backups/*}\332A\004name\022\346\001\n"
          + "\014CreateBackup\0222.google.cloud.metastore.v1be"
          + "ta.CreateBackupRequest\032\035.google.longrunn"
          + "ing.Operation\"\202\001\202\323\344\223\002D\":/v1beta/{parent=projects/*/locations/*/services/*}/backups:\006backup\332A\027parent,backup,backup_id\312A\033\n"
          + "\006Backup\022\021OperationMetadata\022\331\001\n"
          + "\014DeleteBackup\0222.google.cloud.metastore.v1beta.Dele"
          + "teBackupRequest\032\035.google.longrunning.Ope"
          + "ration\"v\202\323\344\223\002<*:/v1beta/{name=projects/*/locations/*/services/*/backups/*}\332A\004name\312A*\n"
          + "\025google.protobuf.Empty\022\021OperationMe"
          + "tadata\032L\312A\030metastore.googleapis.com\322A.https://www.googleapis.com/auth/cloud-platformB\356\001\n"
          + "!com.google.cloud.metastore.v1betaB\016MetastoreProtoP\001ZFgoogle.golang.org/"
          + "genproto/googleapis/cloud/metastore/v1beta;metastore\312\002\035Google\\Cloud\\Metastore\\V1beta\352AN\n"
          + "\036compute.googleapis.com/Network\022,projects/{project}/global/networks/{net"
          + "work}b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.FieldMaskProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.protobuf.WrappersProto.getDescriptor(),
              com.google.type.DayOfWeekProto.getDescriptor(),
            });
    internal_static_google_cloud_metastore_v1beta_Service_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_metastore_v1beta_Service_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_Service_descriptor,
            new java.lang.String[] {
              "HiveMetastoreConfig",
              "Name",
              "CreateTime",
              "UpdateTime",
              "Labels",
              "Network",
              "EndpointUri",
              "Port",
              "State",
              "StateMessage",
              "ArtifactGcsUri",
              "Tier",
              "MetadataIntegration",
              "MaintenanceWindow",
              "Uid",
              "MetadataManagementActivity",
              "ReleaseChannel",
              "MetastoreConfig",
            });
    internal_static_google_cloud_metastore_v1beta_Service_LabelsEntry_descriptor =
        internal_static_google_cloud_metastore_v1beta_Service_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_metastore_v1beta_Service_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_Service_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_metastore_v1beta_MetadataIntegration_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_metastore_v1beta_MetadataIntegration_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_MetadataIntegration_descriptor,
            new java.lang.String[] {
              "DataCatalogConfig",
            });
    internal_static_google_cloud_metastore_v1beta_DataCatalogConfig_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_metastore_v1beta_DataCatalogConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_DataCatalogConfig_descriptor,
            new java.lang.String[] {
              "Enabled",
            });
    internal_static_google_cloud_metastore_v1beta_MaintenanceWindow_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_metastore_v1beta_MaintenanceWindow_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_MaintenanceWindow_descriptor,
            new java.lang.String[] {
              "HourOfDay", "DayOfWeek",
            });
    internal_static_google_cloud_metastore_v1beta_HiveMetastoreConfig_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_metastore_v1beta_HiveMetastoreConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_HiveMetastoreConfig_descriptor,
            new java.lang.String[] {
              "Version", "ConfigOverrides", "KerberosConfig",
            });
    internal_static_google_cloud_metastore_v1beta_HiveMetastoreConfig_ConfigOverridesEntry_descriptor =
        internal_static_google_cloud_metastore_v1beta_HiveMetastoreConfig_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_metastore_v1beta_HiveMetastoreConfig_ConfigOverridesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_HiveMetastoreConfig_ConfigOverridesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_metastore_v1beta_KerberosConfig_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_metastore_v1beta_KerberosConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_KerberosConfig_descriptor,
            new java.lang.String[] {
              "Keytab", "Principal", "Krb5ConfigGcsUri",
            });
    internal_static_google_cloud_metastore_v1beta_Secret_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_metastore_v1beta_Secret_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_Secret_descriptor,
            new java.lang.String[] {
              "CloudSecret", "Value",
            });
    internal_static_google_cloud_metastore_v1beta_MetadataManagementActivity_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_metastore_v1beta_MetadataManagementActivity_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_MetadataManagementActivity_descriptor,
            new java.lang.String[] {
              "MetadataExports", "Restores",
            });
    internal_static_google_cloud_metastore_v1beta_MetadataImport_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_metastore_v1beta_MetadataImport_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_MetadataImport_descriptor,
            new java.lang.String[] {
              "DatabaseDump",
              "Name",
              "Description",
              "CreateTime",
              "UpdateTime",
              "State",
              "Metadata",
            });
    internal_static_google_cloud_metastore_v1beta_MetadataImport_DatabaseDump_descriptor =
        internal_static_google_cloud_metastore_v1beta_MetadataImport_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_metastore_v1beta_MetadataImport_DatabaseDump_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_MetadataImport_DatabaseDump_descriptor,
            new java.lang.String[] {
              "DatabaseType", "GcsUri", "SourceDatabase", "Type",
            });
    internal_static_google_cloud_metastore_v1beta_MetadataExport_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_metastore_v1beta_MetadataExport_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_MetadataExport_descriptor,
            new java.lang.String[] {
              "DestinationGcsUri",
              "StartTime",
              "EndTime",
              "State",
              "DatabaseDumpType",
              "Destination",
            });
    internal_static_google_cloud_metastore_v1beta_Backup_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_metastore_v1beta_Backup_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_Backup_descriptor,
            new java.lang.String[] {
              "Name", "CreateTime", "EndTime", "State", "ServiceRevision", "Description",
            });
    internal_static_google_cloud_metastore_v1beta_Restore_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_metastore_v1beta_Restore_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_Restore_descriptor,
            new java.lang.String[] {
              "StartTime", "EndTime", "State", "Backup", "Type", "Details",
            });
    internal_static_google_cloud_metastore_v1beta_ListServicesRequest_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_metastore_v1beta_ListServicesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_ListServicesRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken", "Filter", "OrderBy",
            });
    internal_static_google_cloud_metastore_v1beta_ListServicesResponse_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_metastore_v1beta_ListServicesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_ListServicesResponse_descriptor,
            new java.lang.String[] {
              "Services", "NextPageToken", "Unreachable",
            });
    internal_static_google_cloud_metastore_v1beta_GetServiceRequest_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_metastore_v1beta_GetServiceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_GetServiceRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_metastore_v1beta_CreateServiceRequest_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_metastore_v1beta_CreateServiceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_CreateServiceRequest_descriptor,
            new java.lang.String[] {
              "Parent", "ServiceId", "Service", "RequestId",
            });
    internal_static_google_cloud_metastore_v1beta_UpdateServiceRequest_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_metastore_v1beta_UpdateServiceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_UpdateServiceRequest_descriptor,
            new java.lang.String[] {
              "UpdateMask", "Service", "RequestId",
            });
    internal_static_google_cloud_metastore_v1beta_DeleteServiceRequest_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_cloud_metastore_v1beta_DeleteServiceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_DeleteServiceRequest_descriptor,
            new java.lang.String[] {
              "Name", "RequestId",
            });
    internal_static_google_cloud_metastore_v1beta_ListMetadataImportsRequest_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_cloud_metastore_v1beta_ListMetadataImportsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_ListMetadataImportsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken", "Filter", "OrderBy",
            });
    internal_static_google_cloud_metastore_v1beta_ListMetadataImportsResponse_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_google_cloud_metastore_v1beta_ListMetadataImportsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_ListMetadataImportsResponse_descriptor,
            new java.lang.String[] {
              "MetadataImports", "NextPageToken", "Unreachable",
            });
    internal_static_google_cloud_metastore_v1beta_GetMetadataImportRequest_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_google_cloud_metastore_v1beta_GetMetadataImportRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_GetMetadataImportRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_metastore_v1beta_CreateMetadataImportRequest_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_google_cloud_metastore_v1beta_CreateMetadataImportRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_CreateMetadataImportRequest_descriptor,
            new java.lang.String[] {
              "Parent", "MetadataImportId", "MetadataImport", "RequestId",
            });
    internal_static_google_cloud_metastore_v1beta_UpdateMetadataImportRequest_descriptor =
        getDescriptor().getMessageTypes().get(22);
    internal_static_google_cloud_metastore_v1beta_UpdateMetadataImportRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_UpdateMetadataImportRequest_descriptor,
            new java.lang.String[] {
              "UpdateMask", "MetadataImport", "RequestId",
            });
    internal_static_google_cloud_metastore_v1beta_ListBackupsRequest_descriptor =
        getDescriptor().getMessageTypes().get(23);
    internal_static_google_cloud_metastore_v1beta_ListBackupsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_ListBackupsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken", "Filter", "OrderBy",
            });
    internal_static_google_cloud_metastore_v1beta_ListBackupsResponse_descriptor =
        getDescriptor().getMessageTypes().get(24);
    internal_static_google_cloud_metastore_v1beta_ListBackupsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_ListBackupsResponse_descriptor,
            new java.lang.String[] {
              "Backups", "NextPageToken", "Unreachable",
            });
    internal_static_google_cloud_metastore_v1beta_GetBackupRequest_descriptor =
        getDescriptor().getMessageTypes().get(25);
    internal_static_google_cloud_metastore_v1beta_GetBackupRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_GetBackupRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_metastore_v1beta_CreateBackupRequest_descriptor =
        getDescriptor().getMessageTypes().get(26);
    internal_static_google_cloud_metastore_v1beta_CreateBackupRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_CreateBackupRequest_descriptor,
            new java.lang.String[] {
              "Parent", "BackupId", "Backup", "RequestId",
            });
    internal_static_google_cloud_metastore_v1beta_DeleteBackupRequest_descriptor =
        getDescriptor().getMessageTypes().get(27);
    internal_static_google_cloud_metastore_v1beta_DeleteBackupRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_DeleteBackupRequest_descriptor,
            new java.lang.String[] {
              "Name", "RequestId",
            });
    internal_static_google_cloud_metastore_v1beta_ExportMetadataRequest_descriptor =
        getDescriptor().getMessageTypes().get(28);
    internal_static_google_cloud_metastore_v1beta_ExportMetadataRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_ExportMetadataRequest_descriptor,
            new java.lang.String[] {
              "DestinationGcsFolder", "Service", "RequestId", "DatabaseDumpType", "Destination",
            });
    internal_static_google_cloud_metastore_v1beta_RestoreServiceRequest_descriptor =
        getDescriptor().getMessageTypes().get(29);
    internal_static_google_cloud_metastore_v1beta_RestoreServiceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_RestoreServiceRequest_descriptor,
            new java.lang.String[] {
              "Service", "Backup", "RestoreType", "RequestId",
            });
    internal_static_google_cloud_metastore_v1beta_OperationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(30);
    internal_static_google_cloud_metastore_v1beta_OperationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_OperationMetadata_descriptor,
            new java.lang.String[] {
              "CreateTime",
              "EndTime",
              "Target",
              "Verb",
              "StatusMessage",
              "RequestedCancellation",
              "ApiVersion",
            });
    internal_static_google_cloud_metastore_v1beta_LocationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(31);
    internal_static_google_cloud_metastore_v1beta_LocationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_LocationMetadata_descriptor,
            new java.lang.String[] {
              "SupportedHiveMetastoreVersions",
            });
    internal_static_google_cloud_metastore_v1beta_LocationMetadata_HiveMetastoreVersion_descriptor =
        internal_static_google_cloud_metastore_v1beta_LocationMetadata_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_metastore_v1beta_LocationMetadata_HiveMetastoreVersion_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_LocationMetadata_HiveMetastoreVersion_descriptor,
            new java.lang.String[] {
              "Version", "IsDefault",
            });
    internal_static_google_cloud_metastore_v1beta_DatabaseDumpSpec_descriptor =
        getDescriptor().getMessageTypes().get(32);
    internal_static_google_cloud_metastore_v1beta_DatabaseDumpSpec_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_metastore_v1beta_DatabaseDumpSpec_descriptor,
            new java.lang.String[] {});
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resource);
    registry.add(com.google.api.ResourceProto.resourceDefinition);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.type.DayOfWeekProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
